auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# 簡化的限制配置
limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 8760h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_streams_per_user: 10000
  max_concurrent_tail_requests: 10
  allow_structured_metadata: false

# 簡化的 ingester 配置（單節點模式）
ingester:
  chunk_idle_period: 30m
  chunk_retain_period: 30s
  chunk_block_size: 262144
  chunk_target_size: 1048576
  max_chunk_age: 1h

# 表格管理
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

# 禁用分析
analytics:
  reporting_enabled: false

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent: https://github.com/grafana/loki/blob/main/docs/sources/configure/telemetry.md
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines: 