services:
  # NATS Node 1
  nats-node1:
    image: nats:2.10-alpine
    container_name: nats-node1
    hostname: nats-node1
    ports:
      - "4222:4222"  # Client connections
      - "6222:6222"  # Cluster connections
      - "8222:8222"  # HTTP monitoring
    volumes:
      - ./config/nats-node1.conf:/nats-server.conf:ro
      - ./config/accounts.conf:/accounts.conf:ro
      - ./data/node1:/data
    command: ["-c", "/nats-server.conf"]
    networks:
      - nats-cluster-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # NATS Node 2  
  nats-node2:
    image: nats:2.10-alpine
    container_name: nats-node2
    hostname: nats-node2
    ports:
      - "4223:4222"  # Client connections
      - "6223:6222"  # Cluster connections  
      - "8223:8222"  # HTTP monitoring
    volumes:
      - ./config/nats-node2.conf:/nats-server.conf:ro
      - ./config/accounts.conf:/accounts.conf:ro
      - ./data/node2:/data
    command: ["-c", "/nats-server.conf"]
    networks:
      - nats-cluster-network
    restart: unless-stopped  
    depends_on:
      - nats-node1
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  # NATS Node 3
  nats-node3:
    image: nats:2.10-alpine
    container_name: nats-node3
    hostname: nats-node3
    ports:
      - "4224:4222"  # Client connections
      - "6224:6222"  # Cluster connections
      - "8224:8222"  # HTTP monitoring
    volumes:
      - ./config/nats-node3.conf:/nats-server.conf:ro
      - ./config/accounts.conf:/accounts.conf:ro
      - ./data/node3:/data
    command: ["-c", "/nats-server.conf"]
    networks:
      - nats-cluster-network
    restart: unless-stopped
    depends_on:
      - nats-node1
      - nats-node2
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  # NATS Surveyor - Web UI for monitoring and management (也是 Prometheus Exporter)
  nats-surveyor:
    image: natsio/nats-surveyor:latest
    container_name: nats-surveyor
    hostname: nats-surveyor
    ports:
      - "7777:7777"
    environment:
      - NATS_SURVEYOR_SERVERS=nats://admin:nats123@nats-node1:4222,nats://admin:nats123@nats-node2:4222,nats://admin:nats123@nats-node3:4222
    command: [
      "--servers", "nats://admin:nats123@nats-node1:4222,nats://admin:nats123@nats-node2:4222,nats://admin:nats123@nats-node3:4222",
      "--port", "7777",
      "--addr", "0.0.0.0",
      "--count", "3",
      "--accounts",
      "--jsz", "all"
    ]
    networks:
      - nats-cluster-network
    restart: unless-stopped
    depends_on:
      - nats-node1
      - nats-node2 
      - nats-node3
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7777/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  # NATS Prometheus Exporter - 監控指標導出
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    container_name: nats-exporter
    hostname: nats-exporter
    ports:
      - "7778:7777"  # Prometheus metrics 端點
    command: [
      "-varz", "-connz", "-routez", "-subz", "-jsz=all", "-gatewayz",
      "-port=7777",
      "-addr=0.0.0.0",
      "-DV",  # Debug mode for verbose logging
      "http://nats-node1:8222"
    ]
    networks:
      - nats-cluster-network
    restart: unless-stopped
    depends_on:
      - nats-node1
      - nats-node2
      - nats-node3
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7777/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  # NATS Box - CLI 管理工具容器
  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    hostname: nats-box
    # 不需要端口映射，主要用作管理工具
    environment:
      - NATS_URL=nats://admin:nats123@nats-node1:4222,nats://admin:nats123@nats-node2:4222,nats://admin:nats123@nats-node3:4222
    command: ["sh", "-c", "while true; do sleep 30; done"]  # 保持容器運行
    networks:
      - nats-cluster-network
    restart: unless-stopped
    depends_on:
      - nats-node1
      - nats-node2
      - nats-node3

  # Prometheus - 指標收集和存儲
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - nats-cluster-network
    restart: unless-stopped
    depends_on:
      - nats-surveyor
      - nats-exporter

  # Grafana - 視覺化和儀表板
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - nats-cluster-network
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki

  # Loki - 日誌聚合服務
  loki:
    image: grafana/loki:latest
    container_name: loki
    hostname: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki:ro
      - loki-data:/tmp/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - nats-cluster-network
    restart: unless-stopped

  # Promtail - 日誌收集代理
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    hostname: promtail
    volumes:
      - ./monitoring/promtail:/etc/promtail:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - nats-cluster-network
    restart: unless-stopped
    depends_on:
      - loki

networks:
  nats-cluster-network:
    name: nats-cluster-network
    driver: bridge

volumes:
  nats-node1-data:
    driver: local
  nats-node2-data:
    driver: local  
  nats-node3-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  loki-data:
    driver: local

# Default Connection Information (記錄在註解中):
# =====================================================
# Client Connections:
#   Node 1: localhost:4222
#   Node 2: localhost:4223  
#   Node 3: localhost:4224
#
# Default Accounts & Credentials:
# =====================================================
# Admin Account:
#   Username: admin
#   Password: nats123
#   Permissions: Full access to all subjects
#
# Development Account:  
#   Username: dev-user
#   Password: dev123
#   Permissions: dev.* subjects only
#
# Production Account:
#   Username: prod-user  
#   Password: prod456
#   Permissions: prod.* subjects only
#
# Microservices Account:
#   Username: service-user
#   Password: service789
#   Permissions: services.* subjects with rate limiting
#
# Web UI Access:
# =====================================================
# NATS Surveyor: http://localhost:7777
#
# Monitoring Endpoints:
# =====================================================  
# Node 1 Monitoring: http://localhost:8222
# Node 2 Monitoring: http://localhost:8223
# Node 3 Monitoring: http://localhost:8224 