apiVersion: 1

datasources:
  # Prometheus 數據源 - 用於指標數據
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      incrementalQuerying: false
      intervalFactor: 2

  # Loki 數據源 - 用於日誌數據
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus-uid
          matcherRegex: "trace_id=(\\w+)"
          name: trace_id
          url: "$${__value.raw}" 