apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: backend-service
  labels:
    app: backend-service
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
        version: v1.0.0
    spec:
      containers:
      - name: backend-service
        image: nginx:1.21-alpine  # 臨時使用 nginx 作為佔位符
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        # 從 ConfigMap 載入環境變數
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: APP_ENV
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: APP_PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: LOG_LEVEL
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: POSTGRES_PORT
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: POSTGRES_DATABASE
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: POSTGRES_USERNAME
        - name: REDIS_CLUSTER_HOSTS
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: REDIS_CLUSTER_HOSTS
        - name: REDIS_CLUSTER_MODE
          valueFrom:
            configMapKeyRef:
              name: backend-service-config
              key: REDIS_CLUSTER_MODE
        # 從 Secret 載入敏感資訊
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-service-secret
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-service-secret
              key: REDIS_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-service-secret
              key: JWT_SECRET
        # 健康檢查
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        # 資源限制
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always