apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-service
  labels:
    app: backend-service
spec:
  type: NodePort
  selector:
    app: backend-service
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 30080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-headless
  namespace: backend-service
  labels:
    app: backend-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: backend-service
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP