server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker 容器日誌收集
  - job_name: docker-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      # 解析 Docker JSON 日誌格式
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            attrs:
      # 從 Docker 屬性中提取容器名稱
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      # 提取容器名稱
      - regex:
          expression: '\/(?P<container_name>[^\/]+)$'
          source: tag
      # 解析時間戳
      - timestamp:
          format: RFC3339Nano
          source: time
      # 設置標籤
      - labels:
          container_name:
          stream:
      # 輸出日誌內容
      - output:
          source: output

  # 專門針對 NATS 容器的日誌配置
  - job_name: nats-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nats
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      # 解析 Docker JSON 格式
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            attrs:
      # 提取容器標籤
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      # 只處理 NATS 相關容器
      - match:
          selector: '{job="nats"}'
          stages:
            - regex:
                expression: '\/(?P<container_name>nats-node\d+|nats-surveyor|nats-exporter|nats-box)$'
                source: tag
            # 解析 NATS 日誌級別
            - regex:
                expression: '^\[(?P<log_level>\w+)\]'
                source: output
            # 解析時間戳
            - timestamp:
                format: RFC3339Nano
                source: time
            # 設置標籤
            - labels:
                container_name:
                log_level:
                service: nats
            # 輸出處理後的日誌
            - output:
                source: output

  # Prometheus 和 Grafana 日誌
  - job_name: monitoring-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoring
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            attrs:
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      # 只處理監控相關容器
      - match:
          selector: '{job="monitoring"}'
          stages:
            - regex:
                expression: '\/(?P<container_name>prometheus|grafana|loki|promtail)$'
                source: tag
            - timestamp:
                format: RFC3339Nano
                source: time
            - labels:
                container_name:
                service: monitoring
            - output:
                source: output

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\S+\s+\S+)\s+(?P<hostname>\S+)\s+(?P<service>\S+)(?:\[(?P<pid>\d+)\])?:\s*(?P<message>.*)$'
      - labels:
          hostname:
          service:
      - timestamp:
          format: 'Jan _2 15:04:05'
          source: timestamp 